### ISSUE TITLE
"View [auth.emails.password] not found." ---api/auth/recovery

### ISSUE THREAD

**Issue by ghost** [francescomalatesta/laravel-api-boilerplate-jwt#10]
{
  "message": "View [auth.emails.password] not found.",
  "status_code": 500
}

maybe i need write this blade manually

**Comment by francescomalatesta** [comment]
@jnuc093 can you write here the code that is giving this error?

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/1922095/15579939/5c335620-2399-11e6-99a1-531ce16300c7.png)

**Comment by ghost** [comment]
oh i got it.it's all API.doesn't need View

**Comment by abhijeetkumar** [comment]
I am having same error message when I am trying to reset my password, Please let me know how can I get over this issue.... Need Help....

**Comment by loginov-rocks** [comment]
+1, interested in laravel 5.2
