### ISSUE TITLE
how can this project add a Socialite Providers.

### ISSUE THREAD

**Issue by ghost** [francescomalatesta/laravel-api-boilerplate-jwt#12]
how can this project add a Socialite Providers.

**Comment by francescomalatesta** [comment]
Hi @jnuc093 , the Laravel documentation explains everything about [Socialite and its setup](https://laravel.com/docs/5.1/authentication#social-authentication). Here you can find a [really good article about it](https://mattstauffer.co/blog/using-github-authentication-for-login-with-laravel-socialite). This is not a real issue related to the boilerplate. 

Closing it.
