### ISSUE TITLE
User table not found(default is not Users?)

### ISSUE THREAD

**Issue by Maykonn** [francescomalatesta/laravel-api-boilerplate-jwt#13]
#8 My api after install and run migration to create the default tables(users, etc), returns:

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.user' doesn't exist 
(SQL: select count(*) as aggregate from `user` where `username` = username)
```

I try to change in $table on User entity(model), config/auth.php, etc.
What happens? Laravel table names aren't in plural by default?

**Comment by Maykonn** [comment]
I solve it. Sorry.

**Comment by cluzt** [comment]
could you share the solve?

im creating api for registrer user using jwt. I use default table "users" but strangely it looks for "user" table.
