### ISSUE TITLE
How to generate never expiring token?

### ISSUE THREAD

**Issue by iamrutvik** [francescomalatesta/laravel-api-boilerplate-jwt#17]
I dont want to refresh the token each time after TTL is end. My Once generated token should never expire. 

How could I do this?

**Comment by acekyd** [comment]
Have you tried setting it to 0 @iamrutvik?

**Comment by andrewshostak** [comment]
Change JWT ttl to null in config/jwt.php :

`'ttl' => env('JWT_TTL', null),`

This works in JWTAuth version 1.0, but not in 0.5.

**Comment by francescomalatesta** [comment]
Thank you @andrewshostak . Closing this.
