### ISSUE TITLE
After migrating to server

### ISSUE THREAD

**Issue by sandervanhooft** [francescomalatesta/laravel-api-boilerplate-jwt#19]
Hi @francescomalatesta,

I've migrated this boilerplate to my Laravel Forge environment (via git).
First I needed to manually add the following folders to mitigate the first problems:
- ./bootstrap/cache
- ./storage/framework/cache (excluded services.php file)

The api routes seem to be functioning.

The only resulting error when visiting the app root welcome url is:

```
InvalidArgumentException in Compiler.php line 36:
Please provide a valid cache path.
```

Any clue how to fix this?

I've used the environment included below (masked some sensitive info with <...>):

```
APP_URL=<...>
APP_KEY=base64:<...>
APP_LOCALE=nl
APP_ENV=production
# APP_ENV=local
APP_DEBUG=true

DB_USERNAME=<...>
DB_PASSWORD=<...>
DB_DATABASE=<...>

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

# MAIL_DRIVER=mailgun
# MAILGUN_DOMAIN=<...>
# MAILGUN_SECRET=<...>

API_PREFIX=api
API_VERSION=v1
API_STRICT=false
API_DEBUG=false

API_SIGNUP_TOKEN_RELEASE=true
API_RESET_TOKEN_RELEASE=true
API_RECOVERY_EMAIL_SUBJECT=example@domain.com
```

**Comment by finbmt** [comment]
I don't call method signup, please help me !!!
http://abcd.com/public/api/auth/signup
{"message":"405 Method Not Allowed","status_code":405}

**Comment by francescomalatesta** [comment]
It seems that is something related to server config, not to the boilerplate: [http://stackoverflow.com/questions/38483837/please-provide-a-valid-cache-path](http://stackoverflow.com/questions/38483837/please-provide-a-valid-cache-path). Closing.

**Comment by acekyd** [comment]
Hey @finbmt You get the "405 Method not allowed" when you try accessing a route via a wrong method. The auth routes are to be accessed via POST. Do this and that should be solved

**Comment by finbmt** [comment]
@francescomalatesta, I've tried 
php artisan cache:clear
php artisan config:clear
php artisan view:clear 
Athough I've deleted this project and created it again

@acekyd : i down this project and install it (i don't modify anything)
At [app/Http/api_routes.php] 
$api->post('auth/signup', 'App\Api\V1\Controllers\AuthController@signup');
It've used method POST. I don't understand what no run
I study in https://www.sitepoint.com/how-to-build-an-api-only-jwt-powered-laravel-app/

**Comment by acekyd** [comment]
@finbmt I think there's a miscommunication... I used that link too to get started... The routes are okay, like you said, you didn't modify anything. What i'm referring to is how you access the api endpoints. If you access http://abcd.com/public/api/auth/signup directly in your browser, your browser uses the GET method instead of post. So configure your client that will be connecting to the api to use POST method. Or you can try the chrome extension [POSTMAN ](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=en) to access your api endpoints via the methods you need.

**Comment by finbmt** [comment]
@acekyd thank you for your help !! I've understand my issue :+1:
