### ISSUE TITLE
how to deal with refresh token

### ISSUE THREAD

**Issue by saqueib** [francescomalatesta/laravel-api-boilerplate-jwt#2]
Fantastic work, its saved me lots of time.

I just wanted to how to handle the refresh token, its not covered anywhere

**Comment by francescomalatesta** [comment]
Hi @saqueib and thank you for your interest!

In order to use the refresh token, you must use the `Tymon\JWTAuth\Middleware\RefreshToken`, as shown here:

https://github.com/tymondesigns/jwt-auth/wiki/Authentication#laravel-5-1

The token will be stored into the response header.
Have a nice day!

**Comment by saqueib** [comment]
@francescomalatesta thanks for this boilerplate, I have my project already completed in laravel, I am not able to load `api_routes.php` for API routes, in my project its giving below error, How can I load the routes defined for api?

``` json
message: "The version given was unknown or has no registered routes.",
status_code: 400
```

In Terminal its saying 

```
$ php artisan api:routes
Your application doesn't have any routes.
```

**Comment by francescomalatesta** [comment]
Double check the version you specified. Have you changed something in the RouteServiceProvider?

**Comment by saqueib** [comment]
Found it, i forgot to add this line `require app_path('Http/api_routes.php');` in **RouteServiceProvider**

Thanks, keep it up :+1:
