### ISSUE TITLE
Problem with CORS

### ISSUE THREAD

**Issue by vitalibr** [francescomalatesta/laravel-api-boilerplate-jwt#20]
@francescomalatesta 
Hi! Thank you for sharing your project with us!

I created an application in AngularJS and I'm trying to make calls to the Laravel API:
MyApp (AngularJS): **http://localhost:8080/**
API (Laravel Boilerplate): **http://localhost:8000/**

But I get this error in the browser console:

> XMLHttpRequest cannot load http://localhost:8000/api/auth/login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

I tried to apply the cors middleware (barryvdh/laravel-cors) in api_routes.php but the error remains. I am using the Angle Satellizer to login.

api_routes.php:

```
<?php

$api = app('Dingo\Api\Routing\Router');

$api->version('v1', ['middleware' => 'cors'], function ($api) {

    $api->post('auth/login', 'App\Api\V1\Controllers\AuthController@login');
    $api->post('auth/signup', 'App\Api\V1\Controllers\AuthController@signup');
    $api->post('auth/recovery', 'App\Api\V1\Controllers\AuthController@recovery');
    $api->post('auth/reset', 'App\Api\V1\Controllers\AuthController@reset');

    // example of protected route
    $api->get('protected', ['middleware' => ['api.auth'], function () {     
        return \App\User::all();
    }]);

    // example of free route
    $api->get('free', function() {
        return \App\User::all();
    });

});

```

My config/cors.php:

```
return [
    'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],
];
```

Error:
![Error](https://s31.postimg.org/synyo4vrf/error.png)
![Error](https://s31.postimg.org/4w74t9f4b/error2.jpg)

**Comment by TakesTheBiscuit** [comment]
Did you read https://github.com/barryvdh/laravel-cors ?

It says csrf should be disabled and that you may have to explicitly list the methods allowed?

**Comment by sandervanhooft** [comment]
@vitalibr did you solve this issue? If so, how?

**Comment by francescomalatesta** [comment]
Any news on this? :) @vitalibr

**Comment by francescomalatesta** [comment]
No updates here, apparently. @vitalibr re-open the issue if you still need help.
