### ISSUE TITLE
Laravel 5.3 plans?

### ISSUE THREAD

**Issue by sandervanhooft** [francescomalatesta/laravel-api-boilerplate-jwt#21]
@francescomalatesta, are there plans for upgrading this to Laravel 5.3?

**Comment by Sogl** [comment]
+1

**Comment by alexjose** [comment]
+1

**Comment by limatheus** [comment]
+1

**Comment by francescomalatesta** [comment]
I am thinking about it but nothing planned yet. Will let you know!

**Comment by rickyjwhong** [comment]
- 1

**Comment by DanJFletcher** [comment]
+1

**Comment by francescomalatesta** [comment]
@sandervanhooft @Sogl @alexjose @limatheus @rickyjwhong @DanJFletcher just started to work on the 5.3 version. Hope to publish something in a few days.

**Comment by francescomalatesta** [comment]
Now my boilerplate runs on Laravel 5.3! Closing this :)
