### ISSUE TITLE
Issue with creating new User

### ISSUE THREAD

**Issue by tarhe** [francescomalatesta/laravel-api-boilerplate-jwt#22]
I noticed in an attempt to signup a new user, the Login Function is called and executed even though I never called it directly. I also noticed that the Signup function is called twice thereby creating problems for my script.

Can someone help me with this?

**Comment by acekyd** [comment]
@tarhe this happens only if the `signup_token_release` is set to true in your `config/boilerplate.php`. If you don't want it to login automatically... change this to false

**Comment by francescomalatesta** [comment]
@tarhe sorry, I never received the notification for this issue. @acekyd is right. Closing this one.
