### ISSUE TITLE
route to reset password 

### ISSUE THREAD

**Issue by AbdulazizAlmohsen** [francescomalatesta/laravel-api-boilerplate-jwt#24]
Do I also need to create a view for resetting password? when I get the password reset link from Laravel api in my email, it opens 

NotFoundHttpException in RouteCollection.php line 161:.

how does that work for api ? What do I need to do to let users send their email and passwords to the reset method in AuthController?

**Comment by francescomalatesta** [comment]
This is not something an the boilerplate should do: everyone implements it as he wishes :) I just offer the endpoints. Closing this.
