### ISSUE TITLE
Retrieve the details of a Logged in User 

### ISSUE THREAD

**Issue by almaweb** [francescomalatesta/laravel-api-boilerplate-jwt#25]
Hi,
How to retrieve the details of a Logged in User immediately after they login ?

**Comment by seba8911** [comment]
auth()->user()->name

2016-11-20 15:01 GMT+01:00 almaweb <notifications@github.com>:

**Comment by francescomalatesta** [comment]
This is **not** an issue related to the boilerplate.

Here you can find some info: [https://github.com/tymondesigns/jwt-auth/wiki/Authentication](https://github.com/tymondesigns/jwt-auth/wiki/Authentication).

Closed.
