### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by Naveen95** [francescomalatesta/laravel-api-boilerplate-jwt#28]
Downloaded the zip file and did a composer install. When i ran it. It shows **Whoops, looks like something went wrong.**

**Comment by francescomalatesta** [comment]
You should use `composer create-project`, otherwise check what scripts are defined in the `composer.json` and execute them manually.

Let me know if you solve @Naveen95

**Comment by Naveen95** [comment]
I am new to programming. I have this doubt  If you see , in the signup method of the AuthCOntroller(app/Api/V1/Controllers/AuthController.php)

public function signup(Request $request)
{
$signupFields = Config::get('boilerplate.signup_fields');
$hasToReleaseToken = Config::get('boilerplate.signup_token_release');

I want to know what is this line of code means

$signupFields = Config::get('boilerplate.signup_fields');
$hasToReleaseToken = Config::get('boilerplate.signup_token_release');

I went through the file boilerplate.php inside the config. But i am not able to find anything called signup_fields.

Am i looking in the wrong place ? Please make me understand this. 
i am following your tutorial 
[https://www.sitepoint.com/how-to-build-an-api-only-jwt-powered-laravel-app/]

**Comment by francescomalatesta** [comment]
You're using an old version of the package, use the 5.3 instead.

Also, if you're new to programming probably this is not the best place to start :) This boilerplate make some things easier to do, but you should understand them first in a better way.

Closing this.
