### ISSUE TITLE
Sample code for other laravel apps

### ISSUE THREAD

**Issue by lampsbr** [francescomalatesta/laravel-api-boilerplate-jwt#3]
Hi,
First thanks for creating this piece of code, I was trying to add jwt and cors by my own in laravel, but being new to this framework and these ideas it was going painfully slow. I'm using this project to create an authentication and authorization app and a number of other apps with different goals, all of them authenticating in the first app. But these apps will be written using plain laravel, not angular. Is there some guide or code sample showing how can I manage the user authentication in other apps? 

I think what I'm asking is how can I manage the token and use that "localstorageservice" without angular.
# 

I was able to log in my user using this logic: 
I have a method in a regular controller with this content:

try{
       $ac = new AuthController;
       $retornApi = $ac->login($request);
       return redirect()->action('WelcomeController@index')
          ->withCookie("cookiename",$retornApi->getData()->token);
      }catch(\Exception $e){
        if($e->getMessage() === "Unauthorized"){
          return view('/csd.inicial')->withErrors(['Email and/or password incorrect!']);
        }

But for some reason my application is creating a session everytime it's visited, and users are able to see all my pages. How can I debug this?

**Comment by francescomalatesta** [comment]
Hey @lampsbr , really sorry for the late answer :(

However, in the last month I wrote an article about this project and how to use it with AngularJS, for Sitepoint!

I will let you know when it will be published. :)

**Comment by francescomalatesta** [comment]
Update: here's the article :) 

http://www.sitepoint.com/how-to-build-an-api-only-jwt-powered-laravel-app/

**Comment by francescomalatesta** [comment]
Closing it as in the article I explain how to create a sample app (second part will be published in 8 hours).
