### ISSUE TITLE
Recovery - Authentication Required

### ISSUE THREAD

**Issue by nerijunior** [francescomalatesta/laravel-api-boilerplate-jwt#30]
POST on `/auth/recovery` returns: 

REQUEST:
```
POST /auth/recovery HTTP/1.1
Content-Type: application/json
Host: api.dev
Connection: close
User-Agent: Paw/2.3.1 (Macintosh; OS X/10.12.1) GCDHTTPRequest
Content-Length: 35

{"email":"user@example.com"}
```

RESPONSE:

```json
{
  "message": "Expected response code 250 but got code \"530\", with message \"530 5.7.1 Authentication required\r\n\"",
  "code": 530,
  "status_code": 500
}
```

I'm doing something wrong?

**Comment by marvisais** [comment]
Same here, did you found a fix?

**Comment by seba8911** [comment]
Did u send token in request ?

2017-01-09 20:05 GMT+01:00 Martin Arvisais <notifications@github.com>:

**Comment by ahmadao** [comment]
you need to configure email sending in your .env file

**Comment by g0ld3lux** [comment]
i did change my .env
```
MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=myusername
MAIL_PASSWORD=mypass
MAIL_ENCRYPTION=null
MAIL_ENCRYPTION=tls
```

but i end up with same error...

**Comment by g0ld3lux** [comment]
for the record , ive went to my mailtrap login and add the cors
for my api for the domain im using which is localhost:8000

the default by mailtrap is laravel.dev

this fixes the issue
