### ISSUE TITLE
Composer install

### ISSUE THREAD

**Issue by muizzjames** [francescomalatesta/laravel-api-boilerplate-jwt#31]
hello, sir.
I tried to install composer, but have some problems.
**************************************
Problem 1
    - Installation request for laravel/framework v5.3.23 -> satisfiable by laravel/framework[v5.3.23].
    - laravel/framework v5.3.23 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 2
    - Installation request for phpunit/phpunit 5.6.3 -> satisfiable by phpunit/phpunit[5.6.3].
    - phpunit/phpunit 5.6.3 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 3
    - laravel/framework v5.3.23 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - tymon/jwt-auth 0.5.9 requires illuminate/http ~5.0 -> satisfiable by laravel/framework[v5.3.23].
    - Installation request for tymon/jwt-auth 0.5.9 -> satisfiable by tymon/jwt-auth[0.5.9].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/20-apcu.ini
    - /etc/php/7.0/cli/conf.d/20-apcu_bc.ini
    - /etc/php/7.0/cli/conf.d/20-bcmath.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-igbinary.ini
    - /etc/php/7.0/cli/conf.d/20-intl.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-mcrypt.ini
    - /etc/php/7.0/cli/conf.d/20-msgpack.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.0/cli/conf.d/20-zip.ini
    - /etc/php/7.0/cli/conf.d/25-memcached.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
*****************************
how can I resolve this problem. please help me.

**Comment by francescomalatesta** [comment]
This is not a project-related issue. The output is telling you that `mbstring` and `dom` extensions are missing. It's also telling you how to activate them! :) Closing.
