### ISSUE TITLE
token as string and not in header

### ISSUE THREAD

**Issue by physio** [francescomalatesta/laravel-api-boilerplate-jwt#32]
hello, sorry for my English. how do you pass the token in the head? I did some tests with postman and if I pass the token as a string works, otherwise not.

i read the jwt documentation and i changed 2 string into .htaccess:
`RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]`

but the result is the same.

**Comment by metaclassing** [comment]
In postman, do not use the authorization tab. Use the header tab and specify the Authorization header with Bearer: JWT
![image](https://cloud.githubusercontent.com/assets/1027733/22066983/e5214a94-dd54-11e6-92a3-9f243d7a4730.png)

**Comment by physio** [comment]
Thank you so much
