### ISSUE TITLE
any chance for a 5.4 update ?

### ISSUE THREAD

**Issue by quasiperfect** [francescomalatesta/laravel-api-boilerplate-jwt#34]
@francescomalatesta, any chance for a 5.4 update ?

**Comment by francescomalatesta** [comment]
Will do asap :)

**Comment by francescomalatesta** [comment]
However, it seems that Dingo is not compatible right now :)

https://github.com/dingo/api/issues/1317

I will wait for "official" support! Stay tuned.

**Comment by 3kynox** [comment]
Adding my voice here, also for new passport features.

I would be also interested to know the process you use for updating. I'll be glad to help as well.

Tks.

**Comment by renege** [comment]
+1

**Comment by francescomalatesta** [comment]
https://github.com/francescomalatesta/laravel-api-boilerplate-jwt/tree/5.4 :)

**Comment by 3kynox** [comment]
Thanks, IT JUST ROCK !!!
