### ISSUE TITLE
Update JWT-auth 0.5.9 to 0.5.10

### ISSUE THREAD

**Issue by kvlknctk** [francescomalatesta/laravel-api-boilerplate-jwt#35]
I need to use JWT-auth with Guards. But tymondesings/jwt-auth 0.5.9 not support guards. 
Would it be a problem if I update to jwt-auth 1.0.0-beta.2 ?
Or do you know how to use guards for [multi-auth](https://www.youtube.com/watch?v=iKRLrJXNN4M&t=1077s)?
Thanks.

**Comment by francescomalatesta** [comment]
Actually I use the boilerplate with the default auth features: never tried with multi-auth. Feel free to open issues if you experience problems with the package.
