### ISSUE TITLE
Token Signature could not be verified and correct middleware name?

### ISSUE THREAD

**Issue by notflip** [francescomalatesta/laravel-api-boilerplate-jwt#37]
**In the documentation api.auth is used as middleware, but in the routes/api.php file jwt.auth is written, which one is the correct one to use?**

Creating a token goes perfect, but when I try to get the '/protected' route in routes/api.php I get the following errors.

When my route middleware is

    $api->group(['middleware' => 'jwt.auth'], function(Router $api) {

    // token_invalid

When my route middleware is api.auth

    $api->group(['middleware' => 'api.auth'], function(Router $api) {

    // Token Signature could not be verified.

**Comment by regal2157** [comment]
I'm having this issue on Mac and Windows. It seems when it's trying to verify the token, the secret is null. and due to that, it'll return the invalid token. Haven't been able yet to dig into it further at this time.

file: src\Providers\JWT\NamshiAdapter.php
```
if (! $jws->verify($this->secret, $this->algo)) {
            throw new TokenInvalidException('Token Signature could not be verified.');
        }
```

**Comment by regal2157** [comment]
Okay - I think I figured it out.

.env is missing a JWT_SECRET key, and you could run
```
php artisan jwt:generate
```
but it doesn't seem to update the .env file. Once you copy the code up to the .env, I was able to get the json response in the file. Though the message is confusing, you'd only get it when authenticated. Even though it sounds like you still need a token - there are no errors.
"Access to this item is only for authenticated user. Provide a token in your request!"

**Comment by notflip** [comment]
Aha yes! Thank you! It's not showing up in the .env file as you're saying. 
For me it's all working now!

**Comment by francescomalatesta** [comment]
Thanks for letting me know guys, it's really strange to see that the jwt token is not generated and added to .env file. I will take a look.

**Comment by Tibo46** [comment]
Hi,

I have run jwt:generate, got a token and added it inside .env file, but I am still getting 
`{
  "error": {
    "message": "Token Signature could not be verified.",
    "status_code": 401
  }
}`
I am correctly passing the header:
`{"Authorization":"Bearer {eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cLzEyNy4wLjAuMTo4MDgwXC9lZHNcLWVhc3lsb3RcL2FwaVwvYXV0aFwvbGfnaW4iLCJpYXQiOjE0OTI1MzA4NTcsImV4cCI6MTQ5MjUzNDQ1NywibmJmIjoxNDsyNTMwODU3LCJqdGkiOiIwZDQyYWZmOTg0NzIyNGRlYmQ1M2U1NjIwZWRkZGQ5NCJ9.f56UcDNID3gEDSMRUDmpTKA6OLiYh1KJ_DXugGNFkAE}"}`
(with and without the { } arroung the token)
Do you guys have any idea what am I missing?

**Comment by notflip** [comment]
Did you try without the quotes around the token? Just leave a space between Bearer and the token.

![screen shot 2017-04-19 at 09 31 58](https://cloud.githubusercontent.com/assets/4146384/25168252/19a8508e-24e3-11e7-8c8f-3ea7efa3896f.png)

**Comment by Tibo46** [comment]
Found it!
My token was actually not valid as the jwt key was changed... My bad!

Keep in mind to regenerate a user token if you change the JWT token :)

**Comment by north9527** [comment]
thanks, it's run.

**Comment by francescomalatesta** [comment]
Closing it, it seems solved. Sorry for the delay, tons of things to do :(

**Comment by casivaagustin-zz** [comment]
I solve this issue running

php artisan jwt:secret

**Comment by selenearzola** [comment]
In my case, the @notflip recommendations help me.  I was wrapping the token in curly braces. Also, I think that there is no need to double check the env var, this because when running php artisan jwt:secret command  the key is set as default value exp:

env('JWT_SECRET', 'secret here')
