### ISSUE TITLE
Possible to combine with regular Auth and web routes?

### ISSUE THREAD

**Issue by notflip** [francescomalatesta/laravel-api-boilerplate-jwt#38]
Is it possible to combine this package with a regular login? And only use the API part for some types of users?

**Comment by francescomalatesta** [comment]
You can probably do it by modifying the call to `JWTAuth::attempt()`. By default, right now, it takes only the classic parameters.

Take a look here: [https://github.com/tymondesigns/jwt-auth/wiki/Creating-Tokens](https://github.com/tymondesigns/jwt-auth/wiki/Creating-Tokens)

Closing this as this is not a real issue of this package :)
