### ISSUE TITLE
Change the protected route message to avoid ambiguity

### ISSUE THREAD

**Issue by ChristianTheMinery** [francescomalatesta/laravel-api-boilerplate-jwt#39]
I'm just getting started with this and am encountering the following issue.

I access the URL via PHP cURL:

`http://localhost/laravel-boilerplate/public/api/protected?token=TOKEN`

And receive the following error:

`{"message":"Access to this item is only for authenticated user. Provide a token in your request!"}`

This despite the fact that the token is very clearly and obviously in the URL as a GET parameter.

I've also attempted to set the token as a HTTP Header:

`curl_setopt($ch, CURLOPT_HTTPHEADER, array('Authorization: Bearer {' . $fields['token'] . '}'));`

Which returns me the exact same error.

It would be one thing if I was getting a `token_invalid` error - which I was earlier, despite the token being the same one provided by the login function - but this now seems to be saying that the token doesn't even exist in the request, even though it obviously does.

**Comment by ChristianTheMinery** [comment]
So I've finally determined that this is partially my error - the message `Access to this item is only for authenticated user. Provide a token in your request!` is what is returned when you _successfully_ connect. However I would still like to leave the issue open as a request to change the wording of that message, as it sounds _very_ much like an error message, not a success message.

**Comment by francescomalatesta** [comment]
A good idea indeed.

**Comment by francescomalatesta** [comment]
Solved [here](https://github.com/francescomalatesta/laravel-api-boilerplate-jwt/tree/5.4.1).

Closing, thanks for the feedback :)
