### ISSUE TITLE
Can't use make:auth

### ISSUE THREAD

**Issue by oliwerhelsen** [francescomalatesta/laravel-api-boilerplate-jwt#4]
Hey,

I need to use the command make:auth but it's not seems to exist, why? And how can i get it back:-)

Thanks in advanced

/O

**Comment by oliwerhelsen** [comment]
You can close this one, i found the issue. You need to upgrade to Laravel 5.2.\* for this to work.

**Comment by francescomalatesta** [comment]
Sorry for the late answer :) another user made a pull request to make this project compatible with L5.2 :) cheers!
