### ISSUE TITLE
Need for api upload route for files (pics, vids, documents etc)

### ISSUE THREAD

**Issue by nfebe** [francescomalatesta/laravel-api-boilerplate-jwt#40]
This is a good idea as most applications today have need to upload stuff for one reason or the other.

**Comment by francescomalatesta** [comment]
Nice idea! Will implement it soon

**Comment by nfebe** [comment]
Glad you see it that way! will be happy to contribute myself, meanwhile waiting for the basic structure you put up.

**Comment by nfebe** [comment]
Done?

**Comment by francescomalatesta** [comment]
Nope, not implemented in this release unfortunately :( In a first time I found it useful, but in the end I prefer to mantain a minimalistic approach and nothing more. Thanks anyway for your interest :)
