### ISSUE TITLE
Non-static method Tymon\\JWTAuth\\JWTAuth

### ISSUE THREAD

**Issue by impactcolor** [francescomalatesta/laravel-api-boilerplate-jwt#42]
message":"Non-static method Tymon\\JWTAuth\\JWTAuth::parseToken() should not be called statically, assuming $this from incompatible context","status_code":500

I'm getting this when I pass over the token do you know any way to resolve it?

**Comment by francescomalatesta** [comment]
Can you give us more context about the error? It also seems something related to the auth package, not the boilerplate itself.

**Comment by impactcolor** [comment]
I actually found the answer to this here: https://github.com/tymondesigns/jwt-auth/issues/104
The JWT-AUTH full path caused the error in a controller I was using.  I saw a couple of people who asked about this in the comments of your tutorial, so I'll explain it here:

I created a new controller and put: use Tymon\JWTAuth\JWTAuth;
This caused the error indicated in the subject line.
I changed it to this: use JWTAuth; 
And it worked.

**Comment by Jason-Nake** [comment]
please instead config\jwt..php : ` 'jwt' => 'Tymon\JWTAuth\Providers\JWT\NamshiAdapter',` as ` 'jwt' => Tymon\JWTAuth\Providers\JWT\Namshi::class`  , `'auth' => 'Tymon\JWTAuth\Providers\Auth\IlluminateAuthAdapter'` as ` 'auth' => Tymon\JWTAuth\Providers\Auth\Illuminate::class` , `'storage' => 'Tymon\JWTAuth\Providers\Storage\IlluminateCacheAdapter'` as ` 'storage' => Tymon\JWTAuth\Providers\Storage\Illuminate::class`
