### ISSUE TITLE
Refresh token issue

### ISSUE THREAD

**Issue by vanushwashere** [francescomalatesta/laravel-api-boilerplate-jwt#43]
I found out that here

```
$api->group(['middleware' => 'jwt.auth'], function(Router $api){

    $api->get('protected', function() {

            return response()->json([
                'message' => 'Access to this item is only for authenticated user. Provide a token in your request!'
            ]);
        });
        $api->get('refresh', [
            'middleware' => 'jwt.refresh',
            function() {
                return response()->json([
                    'message' => 'By accessing this endpoint, you can refresh your access token at each request. Check out this response headers!'
                ]);
            }
        ]);
});
```
`jwt.refresh` middleware  is inside `jwt.auth` middleware, so when I try to refresh expired key I'm getting "token_expired" response, I think that refresh route have to be outside `jwt.auth` middleware group.

**Comment by vanushwashere** [comment]
@francescomalatesta please take a look on it

**Comment by vanushwashere** [comment]
@francescomalatesta :@

**Comment by mcnamee** [comment]
Hi @vanushwashere - I have my refresh endpoint residing outside the `jwt.auth` middleware too, and it's been operating nicely.

**Comment by mayur-padshala** [comment]
@vanushwashere, Refreshing the tokens are for a whole different purpose. You can only refresh a token if the token is valid. If the token you use is expired, you can set the time for which it can be considered as active for longer use. But as a security measure, someone can get a hold of your token and can access the API endpoints. So to prevent that, you need to refresh your token time to time, which is considered a good practise, however is not mandatory. That is why the refresh token route should always be where it is. 

@mcnamee, You should also not put the refresh token routes outside the jwt.auth middleware

**Comment by francescomalatesta** [comment]
@mayur-novus answered to this, closing it.
