### ISSUE TITLE
Multiple Auth with JWT?

### ISSUE THREAD

**Issue by eduardoborges** [francescomalatesta/laravel-api-boilerplate-jwt#44]
how to proced to implemento a multiple auth with JWT?

Example: 
Users (default) and Admins?

**Comment by mcnamee** [comment]
Hi @eduardoborges 
This could be fairly straightforward - 

1. Ensure they're authenticated by putting the route within the `api.auth` middleware
1. Parse/Authenticate the user based on their JWT token (as shown in the repo) - i.e. `JWTAuth::parseToken()->authenticate()` will provide the current user
1. If necessary, based on the user data, do a DB lookup to determine their access level (eg. default or admin)

Now we know what type of user they are, handle the response accordingly (eg. show the respective content or throw an error).

I'd also probably look at creating a middleware, to conveniently protect certain user-type-specific routes too (eg. if a route is only for admins - wrap that route in your new 'admin-user' middleware).

**Comment by Harsukh21** [comment]
please visite this link [](http://laravelcode.com/post/how-to-set-multi-authentication-in-jwt)

**Comment by eduardoborges** [comment]
Thanks!
