### ISSUE TITLE
Two responses

### ISSUE THREAD

**Issue by wyklif** [francescomalatesta/laravel-api-boilerplate-jwt#48]
i am geting two responses when signing up a 200 response and a 201 response
the 200 is {status: "ok"}
and the 201 is {status: "ok", token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjMsI…YzIn0.Kr1UZwp1P1Z84JlQThrb_ewot5kvBTXxWDkNd0cXfad"}

**Comment by francescomalatesta** [comment]
Please give me more details, a single request cannot return two separate responses.

**Comment by francescomalatesta** [comment]
Closing this.

**Comment by wyklif** [comment]
Yeah been away for a while forgot to close this. thanks for the wonderful boilerplate by the way
