### ISSUE TITLE
CORS not working

### ISSUE THREAD

**Issue by aidanbigg** [francescomalatesta/laravel-api-boilerplate-jwt#57]
I've added CORS in the relevant places:

Kernal.php

`protected $routeMiddleware = [
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'cors' => \Barryvdh\Cors\HandleCors::class, // HERE

        'jwt.auth' => GetUserFromToken::class,
        'jwt.refresh' => RefreshToken::class,
    ];`

And routes/api.php

`$api->version('v1', ['middleware' => 'cors'], function (Router $api) {`

And I've configured cors to only allow from http://google.com (as a test, to make sure it works)

config/cors.php

`'supportsCredentials' => false,
    'allowedOrigins' => ['http://google.com'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],`

However it's not throwing an error when making requests, like i'd expect it too.

Am I missing something here?

**Comment by ganey** [comment]
I'm having the same issue and am not seeing the 'Access-Control-Allow-Origin' header in any responses.

**Comment by zhdanovartur** [comment]
You need to add `\Barryvdh\Cors\HandleCors::class` to `$middleware` in `Kernel.php`.

**Comment by aidanbigg** [comment]
@zhdanovartur This resolves the issue, thanks.

**Comment by notflip** [comment]
Shouldn't it be enough to add HandleCors::class to the 'api' middleware group in kernel.php?
It doesn't seem to be working, but the routes are all in the 'api' middleware group in api.php
