### ISSUE TITLE
ModelFactory.php seeding users cant not login

### ISSUE THREAD

**Issue by acfasj** [francescomalatesta/laravel-api-boilerplate-jwt#58]
Since User model has setPasswordAttribute method,   when create a user it will hash the password automatically. But in ModelFactory.php it was been already hashed
`
// ModelFactory.php
'password' => $password ?: $password = bcrypt('password'),

// User.php
public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }
`

**Comment by francescomalatesta** [comment]
Remove the setter if not necessary, the extra code I provide is just an utility :) closing this, thanks
