### ISSUE TITLE
how to update laravel 5.2 ? 

### ISSUE THREAD

**Issue by kvlknctk** [francescomalatesta/laravel-api-boilerplate-jwt#6]
i was update my laravel but its dont work. 
`{"error":{"message":"Auth guard [] is not defined.","status_code":500}}{"error":{"message":"Auth guard [] is not defined.","status_code":500}}`

**Comment by francescomalatesta** [comment]
First of all, have you tried with a fresh new install of it?

**Comment by kvlknctk** [comment]
yes, i tried. its works normal. i changed laravel version on composer.json.

> "require": {
>     "php": ">=5.5.9",
>     "laravel/framework": "5.2._",
>     "tymon/jwt-auth": "0.5._",
>     "dingo/api": "1.0._@dev",
>     "barryvdh/laravel-cors": "^0.7.1",
>     "zizaco/entrust": "dev-laravel-5",
>     "simplesoftwareio/simple-qrcode": "~1"
>   },
>   "require-dev": {
>     "fzaninotto/faker": "~1.4",
>     "mockery/mockery": "0.9._",
>     "phpunit/phpunit": "~4.0",
>     "phpspec/phpspec": "~2.1"
>   },

composer update and first error. Auth guard..

By the way i removed this line on config\app.php
`Illuminate\Routing\ControllerServiceProvider::class,
`
because after updating error *"ControllerServiceProvider" not found. *

**Comment by francescomalatesta** [comment]
You probably used an old version, because if you take a look to the `config/app.php` the `Illuminate\Routing\ControllerServiceProvider::class,` line isn't present :)

Closing it, if you need more info let me know
