### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by zhdanovartur** [francescomalatesta/laravel-api-boilerplate-jwt#61]
API returns 500 HTTP status code on `/user/me` for unauthenticated requests:
```
{
"error":{
    "message": "Unauthenticated.",
    "status_code": 500
  }
}
```
but I expect 401.

**Comment by zhdanovartur** [comment]
The problem is [here](https://github.com/francescomalatesta/laravel-api-boilerplate-jwt/blob/34f1900b37b6bd9160a49b8dd66c2ffa83655bf6/app/Api/V1/Controllers/UserController.php#L22)
Use following:

``` $this->middleware('api.auth', []);``` 

instead of 

``` $this->middleware('auth:api', []);```

 to fix it.

**Comment by francescomalatesta** [comment]
The correct one is "jwt.auth", closing
