### ISSUE TITLE
Default table User

### ISSUE THREAD

**Issue by rebekos** [francescomalatesta/laravel-api-boilerplate-jwt#62]
How to change the default table/model (User) for JWT authentication ?

**Comment by fahadbinashraf** [comment]
I think you can do that by changing the model class inside config/auth.php providers array

```php
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],
```
you would then need to extend that other model class with Authenticatable and implement JWTSubject interface and its methods like the default User model class

**Comment by francescomalatesta** [comment]
Closing it as not strictly related to the boilerplate :)

**Comment by mastercho** [comment]
I change from Users to User but still looking for Users...
