### ISSUE TITLE
How do I change my credentials?

### ISSUE THREAD

**Issue by dhsananias** [francescomalatesta/laravel-api-boilerplate-jwt#63]
How do I change my credentials? For example, currently it considers email and password, I would like to switch to login and password, how do I do this?

**Comment by fahadbinashraf** [comment]
simply change email to another column name (in your case login) in LoginController and then you have to pass login instead of email in your request

**Comment by dhsananias** [comment]
For some reason, at the time of registering, it says that there is no password in the requisition And there, it locks all the registrations saying that "The password is required"

**Comment by francescomalatesta** [comment]
Take a look to https://github.com/francescomalatesta/laravel-api-boilerplate-jwt/blob/master/config/boilerplate.php

**Comment by fahadbinashraf** [comment]
@hananiamizrahi as francescomalatesta mentioned, you need to update the validation rules for signup/login in config/boilerplate.php according to your requirements.
