### ISSUE TITLE
Auth::guard()->attempt($credentials) returns false

### ISSUE THREAD

**Issue by notflip** [francescomalatesta/laravel-api-boilerplate-jwt#67]
I always get a 403 error, the user exists in my database. Any idea what might be happening?

**Comment by notflip** [comment]
Woops! My test password wasn't hashed in the database.
Thanks for this library!

**Comment by erickcastrillo** [comment]
I am experiencing the same issue here. I am getting a 403 Forbiden error message that comes from the line 27 of LoginController

**Comment by mastercho** [comment]
Got same issue and cant solve it
