### ISSUE TITLE
Token not provided on Logout

### ISSUE THREAD

**Issue by notflip** [francescomalatesta/laravel-api-boilerplate-jwt#68]
I get this error when posting to the logout route? Do I need to provide the token for logging out?

**Comment by quantumhype** [comment]
Yes. 

The logout controller uses the jwt.auth middleware, so you'll need to provide the token on logout. 
https://github.com/francescomalatesta/laravel-api-boilerplate-jwt/blob/master/app/Api/V1/Controllers/LogoutController.php

**Comment by notflip** [comment]
Thanks for your response, Is it necessary? Would it be a bad idea to move the logout out of the jwt.auth middleware? Since I can't imagine why a logout function needs a token.

**Comment by quantumhype** [comment]
Yes, the token is necessary. If the user is logged in, then they should have a valid token which is used to authenticate them and gives them authorization to log out. I believe the Tymon/JWT library will also invalidate the token. If they didn't provide a token, then how would you authenticate the user and log them out?

**Comment by notflip** [comment]
You're right! Wasn't thinking clearly. Thank you!
