### ISSUE TITLE
using jwt.refresh for tokens

### ISSUE THREAD

**Issue by apaleja** [francescomalatesta/laravel-api-boilerplate-jwt#7]
Hi There, 

Great boilerplate to start with for API. 

I'd like to know what is the best way to use `jwt.refresh` to refresh token rather getting error `Token is expired`.

I see that `jwt.refresh` is defined in routeMiddleware, so 

```
$api->get('protected', ['middleware' => ['before' => 'api.auth', 'after' => 'jwt.refresh'], function () {
    return User::all();
}]);
```

but I don't think this is working. any better way ?

**Comment by francescomalatesta** [comment]
Hi @apaleja , `jwt.refresh` works exactly like is explained on the [original package wiki page](https://github.com/tymondesigns/jwt-auth/wiki/Authentication#laravel-5-1), this is just a wrapper! :)

If you take a look to [the source code of the middleware](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Http/Middleware/RefreshToken.php), all it does is to set an header. So, in this case, there's no big difference between `before` and `after`. All you need to know is that you will have to save the fresh token into your client.

Cheers!

Closing it, it should be a good explanation :)
