### ISSUE TITLE
SIGN_UP_RELEASE_TOKEN doesn't work

### ISSUE THREAD

**Issue by medmin** [francescomalatesta/laravel-api-boilerplate-jwt#74]
Hi, I have set the following two options to be `true` in the `.env` file, but I still cannot get token, `only` a json `{status:'ok'}`.

Would you like to help me ? Thanks.

```bash
SIGN_UP_RELEASE_TOKEN=true
PASSWORD_RESET_RELEASE_TOKEN=true
```

**Comment by medmin** [comment]
OK, I just figured it out.

For anyone who faces the same problem, use `php artisan config:cache`.

**Comment by mcnamee** [comment]
Thanks for responding with the answer @medmin 
Would you mind closing the issue, now that it's solved?
