### ISSUE TITLE
RuntimeException in DingoServiceProvider.php line 82: Unable to boot ApiServiceProvider, configure an API domain or prefix.

### ISSUE THREAD

**Issue by MohammedSobhei** [francescomalatesta/laravel-api-boilerplate-jwt#8]
What's the problem, I'm just clone the package and then composer install

can you help me?

thanks

**Comment by francescomalatesta** [comment]
Can you be more specific @MohammedSobhei ?

When you get this error? During the install procedure, or in a second moment?

**Comment by jadjoubran** [comment]
You need to have `API_PREFIX=api` (for example) in your `.env`
Another option would be to configure a subdomain but the prefix is much easier
[dingo api prefix docs](https://github.com/dingo/api/wiki/Configuration#prefixes-and-subdomains)

**Comment by francescomalatesta** [comment]
Closing this as getting no answers :) thanks @jadjoubran !
