### ISSUE TITLE
How to implement Email Verification after Registration

### ISSUE THREAD

**Issue by haizad** [francescomalatesta/laravel-api-boilerplate-jwt#82]
What have I done so far..
//User.php
namespace App;
use Illuminate\Contracts\Auth\MustVerifyEmail;
class User extends Authenticatable implements JWTSubject, MustVerifyEmail
{
...

//.env
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=xxxx
MAIL_PASSWORD=xxxxxx
MAIL_ENCRYPTION=tls

any helps?

**Comment by tarhe** [comment]
On successful registration, send a mail to the user with a link to confirm the email. This should be implemented on the main website.

**Comment by francescomalatesta** [comment]
Not related to the boilerplate. Please don't open issues that are not related to the project.
