### ISSUE TITLE
Using Laravel Voyager as a cms Unable to log in

### ISSUE THREAD

**Issue by wyklif** [francescomalatesta/laravel-api-boilerplate-jwt#83]
Hello, thanks for the wonderful package, I am trying to use this package https://github.com/the-control-group/voyager as a kind of cms then i serve its content through your API boilerplate, i have both installed but the problem is that i cannot seem to log in using voyager i always get a 302,  web login doesn't seem to work when using your package i have even tried generating the laravel auth scaffold and trying from there with the same results
I would really appreciate your help
Thanks

**Comment by francescomalatesta** [comment]
Thanks for writing. However, this doesn't seem related to my package but to something related to Voyager, closing it. Issues should be opened only if related to the package.
