### ISSUE TITLE
can't not list route v1/auth/auth-xxx

### ISSUE THREAD

**Issue by ghost** [francescomalatesta/laravel-api-boilerplate-jwt#9]
➜  laravel-api-boilerplate-jwt git:(master) ✗ artisan route:list
+--------+----------+-----+------+---------+------------+
| Domain | Method   | URI | Name | Action  | Middleware |
+--------+----------+-----+------+---------+------------+
|        | GET|HEAD | /   |      | Closure | web        |
+--------+----------+-----+------+---------+------------+
➜  laravel-api-boilerplate-jwt git:(master) ✗

can't not list route v1/auth/auth-xxx ,after composer install

**Comment by francescomalatesta** [comment]
https://github.com/dingo/api/wiki/Creating-API-Endpoints#viewing-routes-in-the-console

**Comment by ghost** [comment]
➜  laravel-api-boilerplate-jwt git:(master) ✗ artisan api:routes
+------+----------+--------------------+------+------------------------------------------------+-----------+------------+----------+------------+
| Host | Method   | URI                | Name | Action                                         | Protected | Version(s) | Scope(s) | Rate Limit |
+------+----------+--------------------+------+------------------------------------------------+-----------+------------+----------+------------+
|      | POST     | /api/auth/login    |      | App\Api\V1\Controllers\AuthController@login    | No        | v1         |          |            |
|      | POST     | /api/auth/signup   |      | App\Api\V1\Controllers\AuthController@signup   | No        | v1         |          |            |
|      | POST     | /api/auth/recovery |      | App\Api\V1\Controllers\AuthController@recovery | No        | v1         |          |            |
|      | POST     | /api/auth/reset    |      | App\Api\V1\Controllers\AuthController@reset    | No        | v1         |          |            |
|      | GET|HEAD | /api/protected     |      | Closure                                        | Yes       | v1         |          |            |
|      | GET|HEAD | /api/free          |      | Closure                                        | No        | v1         |          |            |
+------+----------+--------------------+------+------------------------------------------------+-----------+------------+----------+------------+

Thanks a lot.
